[build]
  command = "yarn install --ignore-engines && yarn run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  
# 反向代理 CORS 资源
[[redirects]]
  from = "/cos.amiyabot.com/*"
  to = "https://cos.amiyabot.com/:splat"
  status = 200
  force = false
  # 即使 dist 目录下有同名文件，也强制走代理。

# 示例：另一个代理
[[redirects]]
  from = "/example.anka1.top/*"
  to = "https://example.anka1.top/:splat"
  status = 200
  force = false