name: Deploy

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 18.x ]

        steps:
            -   name: Fetch sources
                uses: actions/checkout@v2

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Build
                run: |
                    npm install -g yarn
                    yarn install
                    yarn run build

            -   name: Update CNAME
                run:
                    echo 'console.amiyabot.com' > dist/CNAME

            -   name: Deploy
                uses: crazy-max/ghaction-github-pages@v2.5.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    target_branch: gh-pages
                    build_dir: dist
