name: Font Optimization

on:
    push:
        branches: [ master ]

jobs:
    Optimization:

        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.4.2

            -   name: Use Python 3.8
                uses: actions/setup-python@v4
                with:
                    python-version: '3.8'

            -   name: Font Optimization
                env:
                    SECRETID: ${{ secrets.SECRETID }}
                    SECRETKEY: ${{ secrets.SECRETKEY }}
                run: |
                    pip install fontTools cos-python-sdk-v5 brotli
                    python scripts/minfont.py
                    python scripts/uFont.py
